version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true                      # Required to use Docker daemon inside
    user: root                            # Run Jenkins as root so Docker works
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Give Jenkins access to host Docker
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  jenkins_home:
